#!/bin/bash
#pwd
#whoami
# Задаём текущую рабочую директорию

echo "Bash script local server\nlocal Server run:"
#sudo docker run nats-streaming -V


nats-streaming-server -cid test-cluster -store file -dir store


#--file_slice_max_msgs 100 --max_msgs 1000


