#!/bin/bash
#pwd
#whoami
# Задаём текущую рабочую директорию

echo "Bash script \nServer run:"
#sudo docker run nats-streaming -V

sudo docker cp /home/vlad/Programming
sudo docker run -p 4222:4222 nats-streaming -cid test-cluster -store file -dir store


#--file_slice_max_msgs 100 --max_msgs 1000


